name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag node-hello:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker tag node-hello:latest ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:latest
